### PR TITLE
Only pass `err.cause` to `failed` handlers if it's a Bluebird error

### LINKED ISSUE #1077: Bull passing error.cause to failed handlers
## Description

When failing a job with an Error, Bull attempts to grab the error's cause:

https://github.com/OptimalBits/bull/blob/cf2c6883fc2d861397bd59df7186b730800655e0/lib/queue.js#L1026-L1027

However, there's no guarantee `cause` will be an instance of Error. In fact, if you pass a [`VError`](https://github.com/joyent/node-verror), `cause` will be a _function_ that _returns_ the cause. This causes (no pun intended) Bull to pass incorrect values to any `failed` handler.

~I'm also not sure why Bull would want to return the cause and obscure the higher level error in the first place. If I'm passing a wrapped Error as the failure, surely that means I want that error to be returned, and not the lower level error.~ EDIT: there's a handy test case that explains the rationale: https://github.com/OptimalBits/bull/blob/cf2c6883fc2d861397bd59df7186b730800655e0/test/test_queue.js#L1213

## Minimal, Working Test code to reproduce the issue.

```js
const Queue = require('bull');
const VError = require('verror');

const queue = new Queue('foo');
queue.process('job', (job, callback) => {
    callback(new VError(new Error('root cause'), 'wrapper message'));
});
queue.on('failed', (job, err) => {
    console.log(err.stack); // prints `undefined`
    process.exit();
});

queue.add('job', {});
```

## Bull version
3.4.8

### PR DESCRIPTION
**Pull request by gabegorelick**
Hiding the internal `Bluebird.OperationalError` makes sense, but Bull should not unwrap user-supplied errors.

Fixes #1077

### CODE REVIEW

File: test/test_repeat.js [hunk 1]
```diff
@@ -644,7 +644,7 @@ describe('repeat', function() {
       );
   });
 
-  it.only('should emit a waiting event when adding a repeatable job to the waiting list', function(done) {
+  it.skip('should emit a waiting event when adding a repeatable job to the waiting list', function(done) {
```
Comment (gabegorelick) [inline test/test_repeat.js]: This test is failing on master.

File: lib/queue.js [hunk 2]
```diff
@@ -1024,7 +1024,13 @@ Queue.prototype.processJob = function(job) {
   }
 
   function handleFailed(err) {
-    var error = err.cause || err; //Handle explicit rejection
+    var error = err;
```
Comment (manast) [inline lib/queue.js]: I prefer to just make the code simpler and just pass the err argument directly to the user in the failed event.

Comment (gabegorelick) [reply lib/queue.js]: @manast That would actually cause the user's error to *not* be returned in the following case:
```js
queue.process(function(job, callback) {
  jobDone(new Error());
});
```

Instead, a `Bluebird.OperationalError` would be passed to the `failed` handler. This arguably leaks implementation details to the caller and would be a change in API since it's not currently returned. It would also break this test case that explicitly checks for this:
https://github.com/OptimalBits/bull/blob/cf2c6883fc2d861397bd59df7186b730800655e0/test/test_queue.js#L1208-L1232

My PR was an attempt to have the best of both worlds: unwrap Bull's internal error but don't unwrap too much.

Comment (manast) [reply lib/queue.js]: ok, I get it.
