### PR TITLE
[fix test] don't renew a lock that is already released [Fixes #397]

### LINKED ISSUE #397: Error: Unable to renew nonexisting lock
Hi,

It is the 2nd time I'm having this issue in production after upgrading to the latest version `"bull": "^2.0.0"`. I'm still using node `v4.6.0`.

```
Error: Unable to renew nonexisting lock
1 at Object.scripts.takeLock (/home/ubuntu/project/node_modules/bull/lib/scripts.js line 314 col 13)
         throw new Error('Unable to renew nonexisting lock');
2 at Job.takeLock (/home/ubuntu/project/node_modules/bull/lib/job.js line 127 col 18)
         return scripts.takeLock(this.queue, this, renew, ensureActive)
3 at lockRenewer (/home/ubuntu/project/node_modules/bull/lib/queue.js line 644 col 16)
         return job.takeLock(renew, true).then(function(lock){
4 at null.<anonymous> (/home/ubuntu/project/node_modules/bull/lib/timer-manager.js line 80 col 5)
         fn();
5 at ontimeout (timers.js line 198 col 34)
6 at Timer.listOnTimeout (timers.js line 92 col 15)
```

### PR DESCRIPTION
**Pull request by doublerebel**
https://github.com/OptimalBits/bull/issues/397

### CODE REVIEW

File: lib/queue.js [hunk 1]
```diff
@@ -680,6 +686,7 @@ Queue.prototype.processJob = function(job){
     _this.processing--;
     var error = err.cause || err; //Handle explicit rejection
     return job.moveToFailed(err)
+      .then(clearTimer)
```
Comment (manast) [inline lib/queue.js]: don't we have an hazard here where the timer is cleaned *after* we moved to failed?

Comment (bradvogel) [inline lib/queue.js]: How so? The worst case is that it gets renewed after moving to failed, but then immediately released.

File: lib/queue.js [hunk 2]
```diff
@@ -670,6 +675,7 @@ Queue.prototype.processJob = function(job){
       return;
     }
 
+    clearTimer();
```
Comment (bradvogel) [inline lib/queue.js]: I think it'd be slightly more readable to make this a part of the promise chain, eg

```
return clearTimer().
    then(function() {
       return job.moveToCompleted(data);
    })
```
