### PR TITLE
1070 Add discard config for rate-limiter

### LINKED ISSUE #1070: Config option for rate-limiter to do nothing when enabled and hit
## Description

* As apart of the async multi-repo pattern, I would like a config for the rate-limiter to do nothing when it gets hit.
* Currently it throws jobs into the delayed queue.

## Minimal, Working Test code to reproduce the issue.

```typescript
// enabling the rate limiter
const queueOptions = {
  rate: {
      max: 5,
      duration: 1000
    },
};
const queue = new Queue(description, queueOptions);
```

## Bull version
3.4.2

## Additional information

This has been discussed on this issue thread: https://github.com/OptimalBits/bull/issues/1053.
This issue is for tracking the new feature. I will be working on this.

### PR DESCRIPTION
**Pull request by aleccool213**
- Meant for Manually Fetching Jobs pattern

- closes #1070

### CODE REVIEW

File: test/test_rate_limiter.js [hunk 1]
```diff
@@ -69,18 +69,71 @@ describe('Rate limiter', function() {
...
     );
 
-    queue.on('failed', done);
+    queue.on('failed', function(e) {
+      assert.fail(e);
+    });
+  });
+
+  it('should put a job into the delayed queue when limit is hit', function() {
+    queue.on('failed', function(e) {
```
Comment (csingh) [inline test/test_rate_limiter.js]: Might be better to create a new queue here as you did in the test below, since this test assumes that the queue max is set to 1.

File: test/test_rate_limiter.js [hunk 2]
```diff
@@ -69,18 +69,71 @@ describe('Rate limiter', function() {
...
+        return newQueue.add({});
+      })
+    ).then(function() {
+      Promise.all(
+        [1, 2, 3, 4].map(function() {
+          return newQueue.getNextJob();
+        })
+      ).then(function() {
+        return newQueue.getDelayedCount().then(function(delayedCount) {
+          expect(delayedCount).to.eq(0);
```
Comment (csingh) [inline test/test_rate_limiter.js]: Should also do an assert on the main queue to make sure 3 objects are there. Might also want to assert the ordering of the jobs to make sure that is untouched?

File: lib/commands/moveToActive-8.lua [hunk 3]
```diff
@@ -48,8 +49,12 @@ if jobId then
   if(ARGV[6]) then
     local jobCounter
     local maxJobs = tonumber(ARGV[6])
+    local discard = ARGV[8]
     jobCounter = tonumber(rcall("GET", KEYS[6]))
     if jobCounter ~= nil and jobCounter >= maxJobs then
+      if discard == 'true' then
```
Comment (csingh) [inline lib/commands/moveToActive-8.lua]: Are there any tests for these .lua scripts?

File: PATTERNS.md [hunk 4]
```diff
@@ -1,6 +1,4 @@
-
-Patterns
-========
+# Patterns
```
Comment (csingh) [inline PATTERNS.md]: Do we need all these formatting changes in this PR? :) I would remove if unnecessary, its cluttering things up imo

File: REFERENCE.md [hunk 5]
```diff
@@ -68,14 +66,17 @@ interface QueueOptions {
...
 
+When a job gets hit with the rate limiter, it is moved to the delayed queue.
+
 ```typescript
 interface RateLimiter {
-  max: number,      // Max number of jobs processed
-  duration: number, // per duration in milliseconds
+  max: number; // Max number of jobs processed
+  duration: number; // per duration in milliseconds
+  discard: boolean = false; // When jobs get rate limited, nothing happens
```
Comment (csingh) [inline REFERENCE.md]: `discard` might not be the best name for this.. because we're not entirely discarding the rate limiter, we are just disabling the delayed queue. So maybe `disableDelyedQueue` or something similar?

File: test/test_rate_limiter.js [hunk 6]
```diff
@@ -69,18 +69,71 @@ describe('Rate limiter', function() {
...
+      assert.fail(e);
+    });
+  });
+
+  it('should put a job into the delayed queue when limit is hit', function() {
+    queue.on('failed', function(e) {
+      assert.fail(e);
+    });
+
+    return Promise.all(
```
Comment (manast) [inline test/test_rate_limiter.js]: maybe it is just better to write this just as:
```Promise.all([queue.add({}), queue.add({}), queue.add({}), queue.add({})])```

File: REFERENCE.md (hunk 5 above)
Comment (manast) [reply REFERENCE.md]: ok, now I full understand the use-case and discard may indeed not be the best name. I thought the idea was to really throw away the jobs that get "throttled". so this name will be misleading. On the other hand, a name like ```disableDelayedQeuue``` is a bit techie and exposes implementation details.

Comment (manast) [reply REFERENCE.md]: Not sure about this name but what about this alternative ```bounceBack``` ? the option is quite special since it only has use in the manual processing pattern...

File: PATTERNS.md (hunk 4 above)
Comment (aleccool213) [reply PATTERNS.md]: will make another pr

Comment (aleccool213) [reply PATTERNS.md]: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint was used and automatically formatted it for me on save

File: REFERENCE.md (hunk 5 above)
Comment (aleccool213) [reply REFERENCE.md]: I like `bounceBack` 👍

**Comment by aleccool213** [comment]
@manast new review is up 👍
